Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: addToFamily.add_to_family
      Runtime: python3.11
      MemorySize: 1024
      Timeout: 60